const MORSE = {'.-':'A','-...':'B','-.-.':'C','-..':'D','.':'E','..-.':'F','--.':'G','....':'H','..':'I','.---':'J','-.-':'K','.-..':'L','--':'M','-.':'N','---':'O','.--.':'P','--.-':'Q','.-.':'R','...':'S','-':'T','..-':'U','...-':'V','.--':'W','-..-':'X','-.--':'Y','--..':'Z','-----':'0','.----':'1','..---':'2','...--':'3','....-':'4','.....':'5','-....':'6','--...':'7','---..':'8','----.':'9'};
const video = document.querySelector('#inputVideo'), canvas = document.querySelector('#outputCanvas'), ctx = canvas.getContext('2d');
const start = document.querySelector('#startButton'), badge = document.querySelector('#gestureBadge'), status = document.querySelector('#cameraStatus');
const morseEl = document.querySelector('#morseInput'), textEl = document.querySelector('#decodedText'), hint = document.querySelector('#lastSignal');
let code = '', text = '', lastGesture = '', lastAccepted = 0, tracking = false;
const cooldown = 800;
function render() { morseEl.textContent = code || 'Chưa có ký tự'; textEl.textContent = text || '—'; }
function addSignal(signal) { code += signal; lastAccepted = Date.now(); hint.textContent = signal === '.' ? 'Đã thêm chấm' : 'Đã thêm gạch'; render(); }
function commitLetter() { if (!code) return; const char = MORSE[code]; text += char || '�'; hint.textContent = char ? `→ ${char}` : 'Mã chưa hợp lệ'; code = ''; render(); }
function fingersUp(lm) { const tips=[8,12,16,20], pips=[6,10,14,18]; let n=0; if (lm[4].x < lm[3].x) n++; tips.forEach((tip,i)=>{if(lm[tip].y < lm[pips[i]].y) n++;}); return n; }
function labelFor(lm) { const n = fingersUp(lm); return n <= 1 ? 'dot' : n >= 4 ? 'dash' : 'neutral'; }
function setGesture(label) { const labels={dot:'Nắm tay · dấu chấm',dash:'Bàn tay mở · dấu gạch',neutral:'Đổi cử chỉ để tiếp tục'}; badge.textContent=labels[label] || 'Đang chờ tay'; if ((label==='dot'||label==='dash') && label !== lastGesture && Date.now()-lastAccepted>cooldown) addSignal(label==='dot'?'.':'-'); lastGesture=label; }
function onResults(results) { canvas.width=video.videoWidth; canvas.height=video.videoHeight; ctx.save(); ctx.clearRect(0,0,canvas.width,canvas.height); ctx.drawImage(results.image,0,0,canvas.width,canvas.height); if(results.multiHandLandmarks?.length){ const lm=results.multiHandLandmarks[0]; drawConnectors(ctx,lm,HAND_CONNECTIONS,{color:'#c9f26b',lineWidth:4}); drawLandmarks(ctx,lm,{color:'#ff7446',lineWidth:2,radius:3}); setGesture(labelFor(lm)); } else { lastGesture=''; badge.textContent='Đưa một bàn tay vào khung'; } ctx.restore(); }
const hands = new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`}); hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.7,minTrackingConfidence:.7}); hands.onResults(onResults);
start.addEventListener('click', async()=>{ try { start.disabled=true; start.textContent='Đang mở camera…'; const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false}); video.srcObject=stream; await video.play(); new Camera(video,{onFrame:async()=>{await hands.send({image:video})},width:1280,height:720}).start(); tracking=true; document.querySelector('.camera-card').classList.add('active'); status.textContent='Đang nhận diện'; start.textContent='Camera đang bật'; } catch(e) { start.disabled=false; start.textContent='Thử bật lại camera'; status.textContent='Không thể mở camera'; badge.textContent='Hãy cho phép quyền camera'; } });
document.querySelector('#letterButton').onclick=commitLetter; document.querySelector('#spaceButton').onclick=()=>{commitLetter(); text += ' '; render();}; document.querySelector('#backspaceButton').onclick=()=>{code=code.slice(0,-1); hint.textContent='Đã xóa tín hiệu'; render();}; document.querySelector('#clearAll').onclick=()=>{code='';text='';hint.textContent='Đã xóa tất cả';render();}; render();
